version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  build_test_3_7:
    executor:
      name: python/default
      tag: "3.7"
    steps:
      - checkout  # checkout source code to working directory
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: unittest-xml-reporting
          pkg-manager: pip
      - run:
          command: |
            mkdir -p /tmp/testresults
            python -m xmlrunner discover -o /tmp/testresults
      - store_test_results:
          path: /tmp/testresults
  build_test_3_8:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout  # checkout source code to working directory
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: unittest-xml-reporting
          pkg-manager: pip
      - run:
          command: |
            mkdir -p /tmp/testresults
            python -m xmlrunner discover -o /tmp/testresults
      - store_test_results:
          path: /tmp/testresults
  build_test_3_9:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout  # checkout source code to working directory
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: coveralls coverage unittest-xml-reporting
          pkg-manager: pip
      - run:
          command: |
            mkdir -p /tmp/testresults
            coverage run --source=jacobsjsondoc -m xmlrunner discover -o /tmp/testresults
            coveralls
      - store_test_results:
          path: /tmp/testresults
  test_pypi_publish:
    docker:
      - image: circleci/python:3
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to Test PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: circleci/python:3
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*
  safety_check:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout  # checkout source code to working directory
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: safety
          pkg-manager: pip
      - run:
          command: |
            safety check -r requirements.txt
workflows:
  build_test_publish:
    jobs:
      - build_test_3_7
      - build_test_3_8
      - build_test_3_9
      - safety_check
      - python/test:
          version: "3.10"
          pkg-manager: pip
          name: build_test_3_10
      - test_pypi_publish:
          context:
            - python_twine_test
          requires:
            - build_test_3_7
            - build_test_3_8
            - build_test_3_9
            - build_test_3_10
            - safety_check
          filters:
            branches:
              only:
                - next
      - pypi_publish:
          context:
            - python_twine
          requires:
            - build_test_3_7
            - build_test_3_8
            - build_test_3_9
            - build_test_3_10
            - safety_check
          filters:
            branches:
              only:
                - master